set configs.config.server-config.hazelcast-config-specific-configuration.clustering-enabled=false
set configs.config.server-config.hazelcast-config-specific-configuration.enabled=false
set configs.config.server-config.network-config.cache-enabled=false
set configs.config.server-config.ejb-container.property.disable-nonstandard-wrappers=true
set configs.config.server-config.ejb-container.property.disable-auditing=true
set configs.config.server-config.jms-service.type=LOCAL
set configs.config.server-config.jmx-service.jmx-connector.system.enabled=false
set configs.config.server-config.monitoring-service.enabled=false
set configs.config.server-config.request-tracing-service.enabled=false
set configs.config.server-config.microprofile-fault-tolerance-service.enabled=false

# Исправленные команды безопасности
create-file-user --groups users --passwordfile /tmp/payara-password.txt user
