openapi: 3.0.3
info:
  title: HumanBeing Collection API 2
  version: "1.0.0"
  description: |
    RESTful API второй сервис для управления героями и командами.
    - Все объекты передаются и возвращаются в формате JSON (`application/json`).
    - Сервис взаимодействует с первым сервисом (`HumanBeing Collection API`).
servers:
  - url: http://localhost:2468/api/heroes
paths:
  /team/{team-id}/remove-without-toothpick:
    delete:
      tags:
        - Операции с командами
      summary: Удалить из команды всех героев без зубочисток
      description: |
        Удаляет из команды всех героев, не имеющих зубочистки (hasToothpick = false или null).
        Обязательная операция согласно заданию лабораторной работы.
        Операция выполняется через вызов API первого сервиса.
      parameters:
        - name: team-id
          in: path
          description: Уникальный идентификатор команды
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '204':
          description: Герои из команды удалены
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

  /team/{team-id}/car/add:
    post:
      summary: Пересадить всех героев команды, не имеющих автомобиля, на красные "Lada Kalina"
      tags:
        - Операции с командами
      description: |
        Пересаживает всех героев команды, не имеющих автомобиля (car = null),
        на красные "Lada Kalina" (устанавливает car.cool = true).
        Обязательная операция согласно заданию лабораторной работы.
        Операция выполняется через вызов API первого сервиса.
      parameters:
        - name: team-id
          in: path
          description: Уникальный идентификатор команды
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Список героев команды
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HumanBeingList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

components:
  responses:
    BadRequest:
      description: Некорректный запрос
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Ресурс не найден
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServiceUnavailable:
      description: Сервис недоступен
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

    HumanBeing:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          readOnly: true
          description: "Уникальный идентификатор (генерируется автоматически, > 0)"
        name:
          type: string
          minLength: 1
          description: "Не может быть null или пустой строки"
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date-time
          readOnly: true
          description: "Генерируется автоматически на сервере"
        realHero:
          type: boolean
        hasToothpick:
          type: boolean
          nullable: true
        impactSpeed:
          type: integer
          format: int32
          minimum: -441
          description: "Значение поля должно быть больше -442"
        weaponType:
          $ref: '#/components/schemas/WeaponType'
          nullable: true
        mood:
          $ref: '#/components/schemas/Mood'
          nullable: true
        car:
          $ref: '#/components/schemas/Car'
          nullable: true
      required:
        - name
        - coordinates
        - creationDate
        - realHero
        - impactSpeed

    Coordinates:
      type: object
      properties:
        x:
          type: integer
          format: int64
          description: "Поле не может быть null"
        y:
          type: integer
          format: int32
          maximum: 507
          description: "Максимальное значение поля: 507"
      required:
        - x
        - y

    WeaponType:
      type: string
      enum: [ HAMMER, AXE, PISTOL, RIFLE, KNIFE ]

    Mood:
      type: string
      enum: [ SADNESS, SORROW, APATHY, FRENZY ]

    Car:
      type: object
      properties:
        cool:
          type: boolean
      required:
        - cool

    HumanBeingList:
      type: object
      properties:
        humanBeings:
          type: array
          items:
            $ref: '#/components/schemas/HumanBeing'

tags:
  - name: Операции с командами
    description: Дополнительные операции, выполняемые над героями в составе команды
